name: Iris Classifier CI/CD

on:
  push:
    branches: [ main ]  

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v5
      - name: Build Docker Image
        run: docker build -t mlops-flask-app:latest .

      - name: Run Pytest
        run: docker run mlops-flask-app:latest pytest tests/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mlops-flask-app
          IMAGE_TAG: latest
        run: |
          # Tag the image using the registry output from the previous step
          docker tag mlops-flask-app:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # Push the image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }} 
          username: ${{ secrets.EC2_USERNAME }} 
          key: ${{ secrets.EC2_SSH_KEY }}  
          script: |
            # Define variables for cleaner script
            ECR_IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mlops-flask-app:latest
            CONTAINER_NAME=iris-classifier

            # Authenticate to ECR
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            
            # Pull new image
            docker pull $ECR_IMAGE_URI
            
            # Stop and remove old container
            docker stop $CONTAINER_NAME || true 
            docker rm $CONTAINER_NAME || true
            
            # Run new container
            docker run -d -p 80:8080 --name $CONTAINER_NAME $ECR_IMAGE_URI
